- name: Install kubectl (if not exists)
  shell: |
    if ! command -v kubectl > /dev/null
    then
      curl -LO "https://dl.k8s.io/release/stable/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    fi

- name: Install Minikube (if not exists)
  shell: |
    if ! command -v minikube > /dev/null
    then
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      install minikube-linux-amd64 /usr/local/bin/minikube
    fi
