apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-env
  template:
    metadata:
      labels:
        app: flask-env
    spec:
      containers:
         - name: flask-container
           image: flask-env
           imagePullPolicy: Never
           ports:
           - containerPort: 5001
