apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-platform-hpa
  namespace: dev-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{piyush-flask-2c0a12}}
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
