apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-quota
  namespace: dev-platform
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    pods: "20"
    services: "20"
