apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ENV_NAME}}-vpa
  namespace: dev-platform

spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ENV_NAME}}

  updatePolicy:
    updateMode: "Auto"

  resourcePolicy:
    containerPolicies:
    - containerName: app-container
      minAllowed:
        cpu: "100m"
        memory: "128Mi"
      maxAllowed:
        cpu: "500m"
        memory: "512Mi"
