pipeline {
    agent any

    environment {
        STACK = ""
        REPO_URL = "https://github.com/vinay592/SPE_Intelligent-Ephemeral-Multi-Stack-Dev-Platform.git"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Detect Changed Stack') {
            steps {
                script {
                    def changedFiles = sh(
                        script: "git diff --name-only HEAD~1 HEAD",
                        returnStdout: true
                    ).trim()

                    echo "Changed Files: ${changedFiles}"

                    if (changedFiles.contains("templates/flask")) {
                        env.STACK = "flask"
                    } 
                    else if (changedFiles.contains("templates/mern")) {
                        env.STACK = "mern"
                    } 
                    else if (changedFiles.contains("templates/java")) {
                        env.STACK = "java"
                    } 
                    else if (changedFiles.contains("templates/ml")) {
                        env.STACK = "ml"
                    } 
                    else {
                        env.STACK = "flask" // default fallback
                    }

                    echo "Detected STACK: ${env.STACK}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t ${env.STACK}-env:v1 templates/${env.STACK}
                """
            }
        }

        stage('Trigger Deployment (Backend API)') {
            steps {
                sh """
                curl -X POST http://localhost:5001/create-env \
                -H "Content-Type: application/json" \
                -d '{"stack":"${env.STACK}"}'
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh """
                kubectl get pods -n dev-platform
                kubectl get svc -n dev-platform
                """
            }
        }
    }

    post {
        success {
            mail to: 'vinayvb592@gmail.com',
                 subject: "SUCCESS: ${env.STACK} deployed",
                 body: "Build + Deployment successful for ${env.STACK}"
        }
        failure {
            mail to: 'vinayvb592@gmail.com',
                 subject: "FAILED: ${env.STACK}",
                 body: "Pipeline failed. Check Jenkins logs."
        }
    }
}
