pipeline {
    agent any

    parameters {
        choice(
            name: 'STACK',
            choices: ['flask', 'mern', 'java', 'ml'],
            description: 'Choose stack'
        )
    }

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/vinay592/SPE_Intelligent-Ephemeral-Multi-Stack-Dev-Platform.git'
            }
        }

        stage('Ensure Backend Running') {
            steps {
                sh '''
                echo "Checking if backend is running..."

                if lsof -i:5001 | grep LISTEN
                then
                    echo "Backend already running ✅"
                else
                    echo "Starting backend 🚀"
                    nohup python3 backend/app.py > backend.log 2>&1 &
                    sleep 5
                fi
                '''
            }
        }

        stage('Set Minikube Docker Env') {
            steps {
                sh '''
                eval $(minikube docker-env)
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${STACK}-env:v1 templates/${STACK}
                '''
            }
        }

        stage('Trigger Deployment') {
            steps {
                script {
                    def response = sh(
                        script: """
                        curl -s -X POST http://localhost:5001/create-env \
                        -H "Content-Type: application/json" \
                        -d '{"stack":"${STACK}"}'
                        """,
                        returnStdout: true
                    ).trim()

                    echo "DEPLOYMENT RESPONSE: ${response}"
                }
            }
        }

        stage('Show Access Info') {
            steps {
                sh '''
                echo "Fetching services..."
                kubectl get svc -n dev-platform
                '''
            }
        }
    }

    post {
        success {
            mail to: 'vinayvb592@gmail.com',
                 subject: "SUCCESS: ${params.STACK}",
                 body: "Build + Deployment successful 🚀"
        }
        failure {
            mail to: 'vinayvb592@gmail.com',
                 subject: "FAILED: ${params.STACK}",
                 body: "Something went wrong ❌"
        }
    }
}
