input {
  http {
    port => 5044

    additional_codecs => {
      "application/json" => "json"
    }
  }
}

filter {
  mutate {
    rename => {
      "[event]" => "[doc][event]"
      "[user]" => "[doc][user]"
      "[env]" => "[doc][env]"
      "[stack]" => "[doc][stack]"
      "[timestamp]" => "[doc][timestamp]"
      "[log_index]" => "[doc][log_index]"
      "[pod]" => "[doc][pod]"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "platform-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
