input {
  http {
    port => 5044
    codec => "plain"
  }
}

filter {
  # Parse JSON into a specific 'doc' field to avoid any schema collisions
  json {
    source => "message"
    target => "doc"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "platform-logs-%{+YYYY.MM.dd}"
  }
  # Keep this for terminal debugging
  stdout { codec => rubydebug }
}
